spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/game_store_app_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update